import argparse
import sys
from datetime import datetime
from pathlib import Path

from scripts import db
from scripts.logger import get_logger

logger = get_logger("manifest")

# A compact, descriptive view of a catalog: one entry per active document with
# its title, summary, tags, chunk count and locator (uri). The agent reads this
# instead of the DB to decide *whether* to query — cheap browse, low tokens.

_MANIFEST_SQL = """
    SELECT d.doc_id,
           d.filename,
           d.source_type,
           d.title,
           d.summary,
           d.source_uri,
           (SELECT COUNT(*) FROM chunks c WHERE c.doc_id = d.doc_id)        AS n_chunks,
           (SELECT string_agg(t.tag, ', ') FROM tags t WHERE t.doc_id = d.doc_id) AS tags
    FROM documents d
    WHERE d.status = 'active'
    ORDER BY d.source_type, d.filename
"""


def fetch_entries(con) -> list[dict]:
    cols = ["doc_id", "filename", "source_type", "title", "summary",
            "source_uri", "n_chunks", "tags"]
    return [dict(zip(cols, row)) for row in con.execute(_MANIFEST_SQL).fetchall()]


def build_manifest(con, title: str = "Resources Index") -> str:
    entries = fetch_entries(con)
    lines = [
        f"# {title}",
        "",
        "_Generated by the librarian — descriptive index of indexed resources._",
        f"_Updated {datetime.now():%Y-%m-%d %H:%M} · {len(entries)} documents._",
        "",
        "Browse this file first (cheap). To pull the actual text of an entry, query "
        "the catalog:",
        "",
        "```bash",
        'python -m scripts.resources_kb query "<your question>"',
        "```",
        "",
    ]
    if not entries:
        lines.append("_No resources indexed yet. Drop files into `resources/files/` "
                     "and run the ingest command._")
        return "\n".join(lines) + "\n"

    by_type: dict[str, list[dict]] = {}
    for e in entries:
        by_type.setdefault(e["source_type"] or "other", []).append(e)

    for stype in sorted(by_type):
        lines.append(f"## {stype}")
        lines.append("")
        for e in by_type[stype]:
            heading = e["title"] or e["filename"]
            lines.append(f"### {heading}")
            meta = [f"`{e['filename']}`", f"{e['n_chunks']} chunks"]
            lines.append("- " + " · ".join(meta))
            if e["tags"]:
                lines.append(f"- tags: {e['tags']}")
            if e["source_uri"]:
                lines.append(f"- uri: {e['source_uri']}")
            if e["summary"]:
                lines.append("")
                lines.append(e["summary"])
            lines.append("")
    return "\n".join(lines) + "\n"


def write_manifest(con, out_path: str | Path, title: str = "Resources Index") -> Path:
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    text = build_manifest(con, title=title)
    out.write_text(text, encoding="utf-8")
    logger.info(f"Wrote manifest to {out}")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a descriptive INDEX.md from a catalog.")
    parser.add_argument("--db", default="catalog/librarian.duckdb", help="Catalog DB path")
    parser.add_argument("--out", default="INDEX.md", help="Output markdown path")
    parser.add_argument("--title", default="Resources Index")
    args = parser.parse_args()

    try:
        con = db.connect(args.db)
        write_manifest(con, args.out, title=args.title)
    except Exception:
        logger.exception("Manifest generation failed")
        sys.exit(1)


if __name__ == "__main__":
    main()
